In [1]:
# Logistic Regression is a classification solving algorithm
# But the word regression in there for a purpose

In [2]:
# Spam Ham Problem - 
# So we decided that foul words are the major source of SPAMS so we created a dataset for this. 
# No. of NSFW words | SPAM
#                 1 |   No
#                 2 |   No
#                 3 |   No
#                 4 |   No
#                 5 |  Yes
#                 6 |  Yes
#                 7 |  Yes
#                 8 |  Yes
#                 9 |  Yes
#                10 |  Yes 

In [4]:
# Now the story of Logistic Regression - it says LR with build a model which will use
# **REGRESSION** in the backgroud to find the probability if the email is SPAM or HAM

# Now based on probability it will convert the probability into YES or No

# Global Threshold --> 50% 
# IF the probability is equal to or more than 50% than SPAM
# IF the probability is less that 50% than HAM

In [ ]:
# Cancer Dataset
# Plasma_count, Cemo_thep,...........,...,....... CANCER 
# 0.7, 03,........................................YES
# 0.7, 03,........................................YES
# 0.7, 03,........................................NO

# IN this problem we will adjust the threshold to 30% 
# IF the probability is equal to or more than 30% than say YES
# IF the probability is less that 30% than say NO 

In [5]:
from sklearn.datasets import load_iris

In [6]:
iris = load_iris()

In [7]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [9]:
type(iris)

sklearn.utils.Bunch

In [8]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [11]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [12]:
df = pd.DataFrame(data = iris.data, columns=iris.feature_names)

In [13]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [14]:
df["Class"] = iris.target    #class is a reserved keyword 

In [15]:
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  Class
0                5.1               3.5  ...               0.2      0
1                4.9               3.0  ...               0.2      0
2                4.7               3.2  ...               0.2      0
3                4.6               3.1  ...               0.2      0
4                5.0               3.6  ...               0.2      0

[5 rows x 5 columns]

In [16]:
df["Class"].value_counts()

2    50
1    50
0    50
Name: Class, dtype: int64

In [17]:
df.Class.value_counts()

2    50
1    50
0    50
Name: Class, dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   Class              150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [19]:
df.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
Class                0
dtype: int64

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
lr = LogisticRegression()

In [35]:
# df.drop(columns=["Class"])

In [23]:
# lr.fit(X,Y)
# X - input features 
# Y - output features
lr.fit(df.drop(columns=["Class"]), df.Class)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
# 4 input features (sepal L, speal W, petal L , petal W)
# 3 output         (setosa, vericolor, virginica)

In [ ]:
# y_setosa = m1*x1 + m2*x2 + m3*x3 + m4*x4 + c
# y_versicolor = m1*x1 + m2*x2 + m3*x3 + m4*x4 + c
# y_virginica = m1*x1 + m2*x2 + m3*x3 + m4*x4 + c

In [30]:
lr.coef_

array([[-0.41878528,  0.96703041, -2.5209973 , -1.08417682],
       [ 0.53124457, -0.31475282, -0.20008433, -0.94861142],
       [-0.1124593 , -0.65227759,  2.72108162,  2.03278825]])

In [31]:
lr.intercept_

array([  9.84037025,   2.21700109, -12.05737134])

In [36]:
# It has 3 sets of equations(for each flower) and each regresses a 
# probability of that particular flower. 

In [27]:
lr.predict(df.iloc[0:1, 0:4])

array([0])

In [32]:
lr.predict_proba(df.iloc[0:1, 0:4])

array([[9.81801790e-01, 1.81981959e-02, 1.43556907e-08]])

In [33]:
lr.predict_proba(df.iloc[149:150, 0:4])

array([[4.68819654e-04, 2.35001997e-01, 7.64529183e-01]])

In [34]:
lr.predict(df.iloc[149:150, 0:4])

array([2])

In [37]:
np.argmax(lr.predict_proba(df.iloc[149:150, 0:4]))
# tells you **where** is the max probability

2

In [38]:
np.argmin(lr.predict_proba(df.iloc[149:150, 0:4]))
# tells you **where** is the min probability

0

In [40]:
# ------------------------------------------------------------------------------
# PLEASE DONT DO THIS - I AM BAD PERSON AND I AM USING TRAIN DATA FOR TESTING...
# ------------------------------------------------------------------------------
Y_pred = lr.predict(df.drop(columns=["Class"]))

In [43]:
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [44]:
df.Class.values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [46]:
from sklearn.metrics import accuracy_score

In [47]:
accuracy_score(df.Class.values, Y_pred)

0.9733333333333334

In [50]:
# True = 1
# False = 0 
# While you take a sum - you actually count the True values 
(Y_pred == df.Class).sum()/150

0.9733333333333334

In [52]:
# We can even take mean of it
(Y_pred == df.Class).mean()

0.9733333333333334

In [ ]:
# Accuracy is a myth






# Cat Vs Dog 
# Rows - 90 cats and 10 dogs
# Model says that all are cats --- accuracy 90%
# DONT USE ACCURACY AS A METRICS FOR CLASSIFICATION 

# Missclassification - 
# Dogs - 0/10
# Cats - 10/90
# Confusion Matrix/ Recall/ Precision/ F1

# P     C   |    D
# A     90  |   10
#      100  |    0
#--------------------
# T      

In [ ]:
# 100 -> 70 Training + 30 Testing 


In [53]:
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  Class
0                5.1               3.5  ...               0.2      0
1                4.9               3.0  ...               0.2      0
2                4.7               3.2  ...               0.2      0
3                4.6               3.1  ...               0.2      0
4                5.0               3.6  ...               0.2      0

[5 rows x 5 columns]

In [56]:
df.loc[:, ["Class", "petal length (cm)", "sepal length (cm)"]]

Class  petal length (cm)  sepal length (cm)
0        0                1.4                5.1
1        0                1.4                4.9
2        0                1.3                4.7
3        0                1.5                4.6
4        0                1.4                5.0
..     ...                ...                ...
145      2                5.2                6.7
146      2                5.0                6.3
147      2                5.2                6.5
148      2                5.4                6.2
149      2                5.1                5.9

[150 rows x 3 columns]